/* ==== start script ==== */
setTimeout(function () {
    m3D.init(
        [
            { src: 'https://i.imgur.com/OEroF2Mh.jpg' },
            { src: 'https://i.imgur.com/o3x6A1th.jpg' },
            { src: 'https://i.imgur.com/Kl5VhS1h.jpg' },
            { src: 'https://i.imgur.com/4ATHCKjh.jpg' },
            { src: 'https://i.imgur.com/R5PtdRVh.jpg' },
            { src: 'https://i.imgur.com/xRoSMPJh.jpg' },
            { src: 'https://i.imgur.com/MGKFhIRh.jpg' },
            { src: 'https://i.imgur.com/viEeXxgh.jpg' },
            { src: 'https://i.imgur.com/FBfKYn0h.jpg' },
            { src: 'https://i.imgur.com/9DZteHeh.jpg' },
            { src: 'https://i.imgur.com/JyhY1Xwh.jpg' },
            { src: 'https://i.imgur.com/TRe8hP9h.jpg' },
            { src: 'https://i.imgur.com/IDHuigZh.jpg' },
            { src: 'https://i.imgur.com/dy37x1oh.jpg' },
            { src: 'https://i.imgur.com/O9bnSxyh.jpg' },
            { src: 'https://i.imgur.com/RNjC9Ifh.jpg' },
            { src: 'https://i.imgur.com/KU9gYr9h.jpg' },
            { src: 'https://i.imgur.com/21PZ6Ebh.jpg' },
            { src: 'https://i.imgur.com/scCI95Lh.jpg' },
            { src: 'https://i.imgur.com/lCdN1Lqh.jpg' },
            { src: 'https://i.imgur.com/4miGB91h.jpg' },
            { src: 'https://i.imgur.com/telRBrFh.jpg' },
            { src: 'https://i.imgur.com/jnEv6U5h.jpg' },
            { src: 'https://i.imgur.com/tT1Oyfeh.jpg' },
            { src: 'https://i.imgur.com/vWhwCePh.jpg' },
            { src: 'https://i.imgur.com/d1IrTQIh.jpg' },
            { src: 'https://i.imgur.com/W0gsuLRh.jpg' },
            { src: 'https://i.imgur.com/oxfu1u9h.jpg' },
            { src: 'https://i.imgur.com/e0nCfvGh.jpg' },
            { src: 'https://i.imgur.com/gqwfVOnh.jpg' },
            { src: 'https://i.imgur.com/ZhjoZ4Hh.jpg' },
            { src: 'https://i.imgur.com/40C2Zk1h.jpg' },
            /*{ src: 'https://i.imgur.com/n2tR87M.jpg' },
            { src: 'https://i.imgur.com/pJpV8st.jpg' },
            { src: 'https://i.imgur.com/cLfyfpS.jpg' },
            { src: 'https://i.imgur.com/9dXAmDX.jpg' },
            { src: 'https://i.imgur.com/sYHJQlt.jpg' },
            { src: 'https://i.imgur.com/NuReJ3x.jpg' },
            { src: 'https://i.imgur.com/TCfLXoz.jpg' },
            { src: 'https://i.imgur.com/fleK9tN.jpg' },
            { src: 'https://i.imgur.com/xPxvQbt.jpg' },
            { src: 'https://i.imgur.com/3UEr9Aj.jpg' },
            { src: 'https://i.imgur.com/RfUDS7d.jpg' },
            { src: 'https://i.imgur.com/OPXOSK6.jpg' },
            { src: 'https://i.imgur.com/u5KpZ5w.jpg' },
            { src: 'https://i.imgur.com/z5oVPd7.jpg' },
            { src: 'https://i.imgur.com/ppxnM27.jpg' },
            { src: 'https://i.imgur.com/3g9UQv5.jpg' },
            { src: 'https://i.imgur.com/rOwhnvx.jpg' },
            { src: 'https://i.imgur.com/AFaJLtQ.jpg' },
            { src: 'https://i.imgur.com/tLdBrs6.jpg' },
            { src: 'https://i.imgur.com/DDkdokN.jpg' },
            { src: 'https://i.imgur.com/8FSIjGd.jpg' },
            { src: 'https://i.imgur.com/4wmk0qx.jpg' },
            { src: 'https://i.imgur.com/I5aoInL.jpg' },
            { src: 'https://i.imgur.com/w5vRkHt.jpg' },
            { src: 'https://i.imgur.com/nTqFfiJ.jpg' },
            { src: 'https://i.imgur.com/gjOwoc1.jpg' },
            { src: 'https://i.imgur.com/SLHl0hJ.jpg' },
            { src: 'https://i.imgur.com/AWusfLW.jpg' },
            { src: 'https://i.imgur.com/2xTB41c.jpg' },
            { src: 'https://i.imgur.com/BtqSE7a.jpg' },
            { src: 'https://i.imgur.com/9PNqilk.jpg' },
            { src: 'https://i.imgur.com/QOTJdsG.jpg' },
            { src: 'https://i.imgur.com/Bud3Ewr.jpg' },
            { src: 'https://i.imgur.com/cmYhjBs.jpg' },
            { src: 'https://i.imgur.com/5aAg3ha.jpg' },
            { src: 'https://i.imgur.com/JCLg0XX.jpg' },
            { src: 'https://i.imgur.com/38sCI7S.jpg' },
            { src: 'https://i.imgur.com/Q281Wrs.jpg' },
            { src: 'https://i.imgur.com/PXbT1CU.jpg' },
            { src: 'https://i.imgur.com/Z0K8POH.jpg' },
            { src: 'https://i.imgur.com/4ibEIPC.jpg' },
            { src: 'https://i.imgur.com/izk091c.jpg' },
            { src: 'https://i.imgur.com/xpmJJ3z.jpg' },
            { src: 'https://i.imgur.com/zabZ2DV.jpg' },
            { src: 'https://i.imgur.com/k9UZtjA.jpg' },
            { src: 'https://i.imgur.com/1fCIuC4.jpg' },
            { src: 'https://i.imgur.com/j2l8PD2.jpg' },
            { src: 'https://i.imgur.com/TeQfs4T.jpg' },
            { src: 'https://i.imgur.com/X6Qv7M3.jpg' },
            { src: 'https://i.imgur.com/TErIzmh.jpg' },
            { src: 'https://i.imgur.com/vzTlysG.jpg' },
            { src: 'https://i.imgur.com/HkldIND.jpg' },
            { src: 'https://i.imgur.com/a5UppIg.jpg' },
            { src: 'https://i.imgur.com/7ZnhKkj.jpg' },
            { src: 'https://i.imgur.com/RSpDIG1.jpg' },*/
        ]
    );
}, 2000);

$(document).ready(() => {
    $('.map__marker').on('touchstart touchend', function (e) {
        e.preventDefault();
        console.log('hover!')
        //$(this).toggleClass('map__marker__hover');
        $(this).children('.map__marker-info').toggleClass('map__marker__hover');
    });
})