/* ==== start script ==== */
setTimeout(function () {
    m3D.init(
        [
            { src: 'https://i.imgur.com/n2tR87M.jpg' },
            { src: 'https://i.imgur.com/pJpV8st.jpg' },
            { src: 'https://i.imgur.com/cLfyfpS.jpg' },
            { src: 'https://i.imgur.com/9dXAmDX.jpg' },
            { src: 'https://i.imgur.com/sYHJQlt.jpg' },
            { src: 'https://i.imgur.com/NuReJ3x.jpg' },
            { src: 'https://i.imgur.com/TCfLXoz.jpg' },
            { src: 'https://i.imgur.com/fleK9tN.jpg' },
            { src: 'https://i.imgur.com/xPxvQbt.jpg' },
            { src: 'https://i.imgur.com/3UEr9Aj.jpg' },
            { src: 'https://i.imgur.com/RfUDS7d.jpg' },
            { src: 'https://i.imgur.com/OPXOSK6.jpg' },
            { src: 'https://i.imgur.com/u5KpZ5w.jpg' },
            { src: 'https://i.imgur.com/z5oVPd7.jpg' },
            { src: 'https://i.imgur.com/ppxnM27.jpg' },
            { src: 'https://i.imgur.com/3g9UQv5.jpg' },
            { src: 'https://i.imgur.com/rOwhnvx.jpg' },
            { src: 'https://i.imgur.com/AFaJLtQ.jpg' },
            { src: 'https://i.imgur.com/tLdBrs6.jpg' },
            { src: 'https://i.imgur.com/DDkdokN.jpg' },
            { src: 'https://i.imgur.com/8FSIjGd.jpg' },
            { src: 'https://i.imgur.com/4wmk0qx.jpg' },
            { src: 'https://i.imgur.com/I5aoInL.jpg' },
            { src: 'https://i.imgur.com/w5vRkHt.jpg' },
            { src: 'https://i.imgur.com/nTqFfiJ.jpg' },
            { src: 'https://i.imgur.com/gjOwoc1.jpg' },
            { src: 'https://i.imgur.com/SLHl0hJ.jpg' },
            { src: 'https://i.imgur.com/AWusfLW.jpg' },/*
            { src: 'https://i.imgur.com/2xTB41c.jpg' },
            { src: 'https://i.imgur.com/BtqSE7a.jpg' },
            { src: 'https://i.imgur.com/9PNqilk.jpg' },
            { src: 'https://i.imgur.com/QOTJdsG.jpg' },
            { src: 'https://i.imgur.com/Bud3Ewr.jpg' },
            { src: 'https://i.imgur.com/cmYhjBs.jpg' },
            { src: 'https://i.imgur.com/5aAg3ha.jpg' },
            { src: 'https://i.imgur.com/JCLg0XX.jpg' },
            { src: 'https://i.imgur.com/38sCI7S.jpg' },
            { src: 'https://i.imgur.com/Q281Wrs.jpg' },
            { src: 'https://i.imgur.com/PXbT1CU.jpg' },
            { src: 'https://i.imgur.com/Z0K8POH.jpg' },
            { src: 'https://i.imgur.com/4ibEIPC.jpg' },
            { src: 'https://i.imgur.com/izk091c.jpg' },
            { src: 'https://i.imgur.com/xpmJJ3z.jpg' },
            { src: 'https://i.imgur.com/zabZ2DV.jpg' },
            { src: 'https://i.imgur.com/k9UZtjA.jpg' },
            { src: 'https://i.imgur.com/1fCIuC4.jpg' },
            { src: 'https://i.imgur.com/j2l8PD2.jpg' },
            { src: 'https://i.imgur.com/TeQfs4T.jpg' },
            { src: 'https://i.imgur.com/X6Qv7M3.jpg' },
            { src: 'https://i.imgur.com/TErIzmh.jpg' },
            { src: 'https://i.imgur.com/vzTlysG.jpg' },
            { src: 'https://i.imgur.com/HkldIND.jpg' },
            { src: 'https://i.imgur.com/a5UppIg.jpg' },
            { src: 'https://i.imgur.com/7ZnhKkj.jpg' },
            { src: 'https://i.imgur.com/RSpDIG1.jpg' },*/
        ]
    );
}, 500);